---

# ferrarimarco.bash-aliases
bash_aliases:
  - { alias: "sshclear", command: "rm ~/.ssh/multiplex/* -f && echo SSH connection cache cleared;"}
  - { alias: "sshlist", command: "echo Currently open ssh connections && echo && l ~/.ssh/multiplex/"}

# grog.package
package_list:
  - name: bash-completion
  - name: bind9-host
  - name: curl
  - name: htop
  - name: mutt
  - name: net-tools
  - name: nmap
  - name: openssh-server
  - name: python
  - name: qemu-guest-agent
  - name: screen
  - name: sudo
  - name: tmux
  - name: tree
  - name: wget