---

target_os: debian

# grog.package
package_list:
  - name: apt-transport-https
  - name: bash-completion
  - name: curl
  - name: lm-sensors

# ironicbadger.ansible_users
users: {}

## telegraf
telegraf_influxdb_urls:
  - http://192.168.1.10:8086
telegraf_influxdb_database: telegraf
telegraf_influxdb_username: root
telegraf_influxdb_password: root
telegraf_plugins_base:
  - name: mem
  - name: system
  - name: cpu
    options:
      percpu: "true"
      totalcpu: "true"
      collect_cpu_time: "false"
      report_active: "false"
  - name: disk
    options:
      ignore_fs:
        - "tmpfs"
        - "devtmpfs"
        - "devfs"
      mountpoints:
        - "/"
  - name: diskio
    options:
      skip_serial_number: "true"
  - name: kernel
  - name: processes
  - name: hddtemp
  - name: net
    options:
      interfaces:
        - "ens192"
  - name: sensors
